cscflow:
  image: dockerhub.cisco.com/sunfish/csc-flowstudio:S01
  labels:
    io.rancher.container.start_once: 'true'
  expose:
   - 1880/tcp
  volumes:
   - /mnt/nfs/var/nfsshare/:/opt/cisco/flowstudio/.data
  environment:
    TOPIC: ${TOPIC}
    MESSAGE: ${MESSAGE}
    FLOW: "SENDMQTT"
