cscflow:
  image: engci-docker.cisco.com:5932/csc-flowstudio
  labels:
    io.rancher.scheduler.affinity:host_label_ne: fname=host01
    io.rancher.container.start_once: 'true'
  expose:
   - 1880/tcp
  volume_driver: csc-convoy-gluster
  volumes:
   - flowstudio:/opt/cisco/flowstudio/.data
  environment:
    TOPIC: ${TOPIC}
    MESSAGE: ${MESSAGE}
    FLOW: "GRANTSVC"
