name: Send A MQTT Message
description: |
  Send a message to an MQTT broker
version: v0.0.1
category: Demo Services
maintainer: Cisco
license: # The license
projectURL: # A URL related to the catalog entry
