cscflow:
  image: dockerhub.cisco.com/sunfish/csc-flowstudio:S01
  labels:
    io.rancher.scheduler.affinity:host_label: fname=host01
    io.rancher.container.start_once: 'true'
  expose:
   - 1880/tcp
  volume_driver: nodeflow-convoy-gluster
  volumes:
   - nodeflow:/opt/cisco/flowstudio/.data
  environment:
    SEND_TO: ${SEND_TO}
    MESSAGE: ${SEND_MESSAGE}
    FLOW: "SENDEMAIL"
