cscflow:
  image: dockerhub.cisco.com/sunfish/csc-flowstudio:satybodd
  labels:
    io.rancher.scheduler.affinity:host_label_ne: FNAME=HOST01
    io.rancher.container.start_once: 'true'
  expose:
   - 1880/tcp
  volume_driver: csc-convoy-gluster
  volumes:
   - flowstudio:/opt/cisco/flowstudio/.data
  environment:
    SEND_TO: ${SEND_TO}
    MESSAGE: ${SEND_MESSAGE}
    FLOW: "SENDEMAIL"
